- name: Add nginx repo
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=present

- name: Add nginx source repo
  apt_repository: repo='deb-src http://nginx.org/packages/ubuntu/ trusty nginx' state=present

- name: Add nginx repo pubkey
  get_url: url=http://nginx.org/keys/nginx_signing.key dest=/root/nginx_signing.key mode=0440

- name: Install nginx
  apt: name=nginx state=latest force=yes update_cache=yes

- name: Install nginx repo pubkey
  command: apt-key add /root/nginx_signing.key

- name: Remove default nginx config
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Remove default nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Remove default nginx config
  file: path=/etc/nginx/conf.d/example_ssl.conf state=absent

- name: Copy nginx config
  copy: src=files/nginx.conf dest=/etc/nginx/conf.d/unsplash.conf

- name: Copy nginx certificate
  copy: src=files/unsplash.crt dest=/etc/ssl/unsplash.crt owner=root group=root mode=0644

- name: Copy nginx certificate key
  copy: src=files/unsplash.key dest=/etc/ssl/unsplash.key owner=root group=root mode=0644

- name: Generate dhparam
  command: chdir=/etc/ssl/certs openssl dhparam -out dhparam.pem 4096
  when: dhparam

- name: Ensure nginx is running
  service: name=nginx state=restarted