---
- name: Install dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - git
    - curl
    - build-essential
  tags: nodejs

- name: Clone n
  git: repo=https://github.com/tj/n.git dest=~/.n
  tags: nodejs

- name: Install n
  shell: make install
  args: 
    chdir: ~/.n
  tags: nodejs

- name: Install nodejs
  command: n 0.12.4
  register: nodejs_install_result
  changed_when: "'installed : ' in nodejs_install_result.stdout"
  tags: nodejs